// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9psW5TpTimLVCX10crIWW16SzlBbXzR0',
    appId: '1:986914028918:web:9805747b53c67e93b60e57',
    messagingSenderId: '986914028918',
    projectId: 'rick-coins-ruhsari',
    authDomain: 'rick-coins-ruhsari.firebaseapp.com',
    storageBucket: 'rick-coins-ruhsari.firebasestorage.app',
    measurementId: 'G-VSN5FNM14L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzK6ib8cPuTvvJx3hzePjDLLYA18b8YaE',
    appId: '1:986914028918:android:cd1507bab4a6b4cdb60e57',
    messagingSenderId: '986914028918',
    projectId: 'rick-coins-ruhsari',
    storageBucket: 'rick-coins-ruhsari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4Q7lVjLH_DxJ-jn5KMu9uUN_RIhqK1Y',
    appId: '1:986914028918:ios:f08a06bdc604ae16b60e57',
    messagingSenderId: '986914028918',
    projectId: 'rick-coins-ruhsari',
    storageBucket: 'rick-coins-ruhsari.firebasestorage.app',
    iosBundleId: 'com.example.rickCoinsMarketRuhsari',
  );
}
